changelog:
  sections:
    - title: ":rocket: Enhancements & Features"
      labels: [ "enhancement", "documentation", "example" ]
    - title: ":bug: Bug Fixes"
      labels: [ "bug" ]
    - title: ":hammer_and_wrench: Chore"
      labels: [ "dependencies" ]
  issues:
    exclude:
      labels: [ "question" ]
  contributors:
    exclude:
      names: [ "dependabot[bot]", "codacy-badger" ]
